(function(CSM,w){if(!CSM.useCel||CSM.ue_cel){return;
}CSM.ue_cel=(function(){var modules=[],loaded=[],externalDependecies=["jQuery"],t0=ue_t0,scopeName="csmCELLSframework",namespace="cel",ue=CSM.ue,uet=CSM.uet,uex=CSM.uex;
function isBackForward(){var perfInterface=w.performance||w.webkitPerformance,backForwardNavTiming=perfInterface&&perfInterface.navigation&&perfInterface.navigation.type==2,backForwardCSMFormValue=document.ue_backdetect&&document.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,backForwardCSMFormInitialValue=ue.bfini;
if(backForwardNavTiming||(backForwardCSMFormInitialValue&&(backForwardCSMFormInitialValue>1))||(!backForwardCSMFormInitialValue&&backForwardCSMFormValue&&(backForwardCSMFormValue>1))){return 1;
}return 0;
}ue.isBF=isBackForward();
if(ue.isBF){ue.log({k:"bft",t:ue.d()},namespace);
return;
}if(typeof uet=="function"){uet("bb",scopeName,{wb:1});
}function switchModules(){var len=modules.length;
if(len>0){var notLoaded=[];
for(var i=0;
i<len;
i++){var module=modules[i].api;
if(module.ready()){module.on({ts:ue.d,ns:namespace});
loaded.push(module);
ue.log({k:"mso",n:modules[i].name,t:ue.d()},namespace);
}else{notLoaded.push(modules[i]);
}}modules=notLoaded;
}}if(w.amznJQ){var len=externalDependecies.length;
for(var i=0;
i<len;
i++){w.amznJQ.available(externalDependecies[i],switchModules);
}}else{if(w.P&&w.P.when){w.P.when("ready",externalDependecies).execute(switchModules);
}}w.amznJQ&&w.amznJQ.declareAvailable("csmCELLS");
function beforeUnloadHandler(e){if(!beforeUnloadHandler.executed){ue.log({k:"eod",t0:ue.t0,t:ue.d()},namespace,{n:1,img:1});
for(var i=0;
i<modules.length;
i++){if(modules[i].off){modules[i].off({ts:ue.d,ns:namespace});
}}beforeUnloadHandler.executed=1;
}}if(ue.attach){if(w.onpagehide||w.onpagehide===null){ue.attach("pagehide",beforeUnloadHandler);
}else{ue.attach("beforeunload",beforeUnloadHandler);
}}else{var prevOnBeforeUnload=w.onbeforeunload;
w.onbeforeunload=function(e){if(typeof prevOnBeforeUnload=="function"){prevOnBeforeUnload(e);
}beforeUnloadHandler(e);
};
}if(typeof uex=="function"){uex("ld",scopeName,{wb:1});
}return{registerModule:function(name,api){modules.push({name:name,api:api});
ue.log({k:"mrg",n:name,t:ue.d()},namespace);
switchModules();
},reset:function(){ue.log({k:"rst",t0:ue.t0,t:ue.d()},namespace);
var len=loaded.length;
for(var i=0;
i<len;
i++){loaded[i].reset();
}}};
})();
})(ue_csm,window);
(function(CSM){if(!CSM.useCel||CSM.ue_pdm){return;
}if(ue.isBF){return;
}CSM.ue_pdm=(function(){var screen,doc,win,sstimer,delta,sstimespan,lastScreenInfo,lastDocInfo,scopeName="csmCELLSpdm",namespace,ue=CSM.ue,uet=CSM.uet,uex=CSM.uex;
if(typeof uet=="function"){uet("bb",scopeName,{wb:1});
}function snapshot(){var screenInfo={w:screen.width,aw:screen.availWidth,h:screen.height,ah:screen.availHeight,cd:screen.colorDepth,pd:screen.pixelDepth};
var docInfo={w:doc.width(),h:doc.height()};
if(!lastScreenInfo||lastScreenInfo.w!=screenInfo.w||lastScreenInfo.h!=screenInfo.h||lastScreenInfo.aw!=screenInfo.aw||lastScreenInfo.ah!=screenInfo.ah||lastScreenInfo.pd!=screenInfo.pd||lastScreenInfo.cd!=screenInfo.cd){lastScreenInfo=screenInfo;
lastScreenInfo.t=delta();
lastScreenInfo.k="sci";
ue.log(lastScreenInfo,namespace);
}if(!lastDocInfo||lastDocInfo.w!=docInfo.w||lastDocInfo.h!=docInfo.h){lastDocInfo=docInfo;
lastDocInfo.t=delta();
lastDocInfo.k="doi";
ue.log(lastDocInfo,namespace);
}sstimer=setTimeout(snapshot,sstimespan);
}function handleBlur(){ue.log({k:"ebl",t:delta()},namespace);
}function handleFocus(){ue.log({k:"efo",t:delta()},namespace);
}return{on:function(options){sstimespan=options.timespan||500;
delta=options.ts;
namespace=options.ns;
win=window.jQuery(window);
doc=window.jQuery(document);
screen=window.screen;
win.bind("blur",handleBlur);
win.bind("focus",handleFocus);
setTimeout(snapshot,0);
if(typeof uex=="function"){uex("ld",scopeName,{wb:1});
}},ready:function(){return window.jQuery?true:false;
},reset:function(){lastDocInfo=null;
lastScreenInfo=null;
}};
})();
if(CSM.ue_cel){CSM.ue_cel.registerModule("page module",CSM.ue_pdm);
}})(ue_csm);
(function(CSM){if(!CSM.useCel||CSM.ue_vpm){return;
}if(ue.isBF){return;
}CSM.ue_vpm=(function(){var lastViewportInfo,sstimer,sstimespan,win,delta,scopeName="csmCELLSvpm",namespace,ue=CSM.ue,uet=CSM.uet,uex=CSM.uex;
if(typeof uet=="function"){uet("bb",scopeName,{wb:1});
}function snapshot(){var viewportInfo={w:win.width(),h:win.height(),x:win.scrollLeft(),y:win.scrollTop()};
if(!lastViewportInfo||lastViewportInfo.w!=viewportInfo.w||lastViewportInfo.h!=viewportInfo.h||lastViewportInfo.x!=viewportInfo.x||lastViewportInfo.y!=viewportInfo.y){viewportInfo.t=delta();
viewportInfo.k="vpi";
lastViewportInfo=viewportInfo;
ue.log(lastViewportInfo,namespace);
}sstimer=setTimeout(snapshot,sstimespan);
}return{on:function(options){win=window.jQuery(window);
delta=options.ts;
namespace=options.ns;
sstimespan=options.timespan||100;
setTimeout(snapshot,0);
if(typeof uex=="function"){uex("ld",scopeName,{wb:1});
}},ready:function(){return window.jQuery?true:false;
},reset:function(){lastViewportInfo=null;
},getVpi:function(){return lastViewportInfo;
}};
})();
if(CSM.ue_cel){CSM.ue_cel.registerModule("viewport module",CSM.ue_vpm);
}})(ue_csm);
(function(CSM){if(!CSM.useCelFF||CSM.ue_fem){return;
}var ue=CSM.ue||{};
if(ue.isBF){return;
}CSM.ue_fem=(function(win,doc){var sstimer,delta,sstimespan,scopeName="csmCELLSfem",namespace,vpi,results={},jQuery,MAX_RUNNING_TIME,SNAPSHOT_DELAY,MAX_WIDGETS_PER_PAGE=25,maxWidgetsExceeded=0,DEFAULT_BEHAVIOR=1,START_AFTER_ONLOAD=3,INCREASED_MAX_RUNNING_TIME=4,NO_SELF_STOP=5,START_AFTER_ONLOAD_1=7,START_AFTER_ONLOAD_2=8,START_AFTER_ONLOAD_3=9,MAX_RUNNING_TIME_20=10,MAX_RUNNING_TIME_30=11,MAX_RUNNING_TIME_50=12,MAX_RUNNING_TIME_100=13,SNAPSHOT_ONE_SECOND=14,logs=[],startTime,timespan,collectedOneShotInfo={},celWidgetsByClassName=[],celWidgetsById=[],stepper=createStepper(3),UNDEFINED,docElement,body;
if(typeof uet=="function"){uet("bb",scopeName,{wb:1});
}function sendLogs(){for(var i=0;
i<logs.length;
i++){ue.log(logs[i],namespace);
}logs=[];
}function createStepper(maxsteps){var step=0;
return{next:function(){step=(step+1)%maxsteps;
},current:function(){return step;
}};
}function snapshot(){startTime=delta();
var currentStep=stepper.current();
if(currentStep==0){detectFeatures();
}else{if(currentStep==1){collectFeaturesInfo();
}else{if(currentStep==2){recordFeatureChanges();
}}}timespan=delta()-startTime;
if((timespan<MAX_RUNNING_TIME&&!maxWidgetsExceeded)||(CSM.useCelFF==NO_SELF_STOP)){sstimer=setTimeout(snapshot,sstimespan);
stepper.next();
}else{if(maxWidgetsExceeded){logs.push({s:timespan,n:currentStep,t:delta(),k:"mwe"});
}logs.push({s:timespan,n:currentStep,t:delta(),k:"mrt"});
}setTimeout(sendLogs,0);
}function detectFeatures(){var selectors=["sims_fbt","vtpsims","purchaseShvl","fallbacksessionShvl","sessionShvl","DAr2","DAr7","DAala1","DAaba0","DAcrt","DAra1","DAga"],celWidgetsClassName="celwidget",length,feature;
celWidgetsByClassName=nativeGetElementsByClassName(celWidgetsClassName);
celWidgetsById=[];
length=selectors.length;
for(i=0;
i<length;
i++){feature=doc.getElementById(selectors[i]);
if(feature){celWidgetsById.push(feature);
}}}function collectFeaturesInfo(){var length=celWidgetsByClassName.length,pageOffset=getPageOffset(),now=delta();
vpi=ue_vpm.getVpi();
if(length<MAX_WIDGETS_PER_PAGE){for(i=0;
i<length;
i++){collectFeatureInfo(now,pageOffset,celWidgetsByClassName[i]);
}}else{maxWidgetsExceeded=1;
}length=celWidgetsById.length;
for(i=0;
i<length;
i++){collectFeatureInfo(now,pageOffset,celWidgetsById[i]);
}}function nativeGetElementsByClassName(className){var result=[];
if(doc.getElementsByClassName){result=doc.getElementsByClassName(className);
}else{if(doc.querySelectorAll){result=doc.querySelectorAll("."+className);
}}return result;
}function recordFeatureChanges(){var now=delta();
for(var name in results){var result=results[name],freshReading=result.fresh,oldReading=result.old,changed;
if(oldReading&&!freshReading){logs.push({n:name,t:now,k:"ewd"});
delete results[name];
}else{if(freshReading){if(oldReading){changed=!compareWithTollerance(freshReading.w,oldReading.w)||!compareWithTollerance(freshReading.h,oldReading.h)||!compareWithTollerance(freshReading.x,oldReading.x)||!compareWithTollerance(freshReading.y,oldReading.y)||freshReading.z!=oldReading.z;
if(changed){logWidgetInfo(freshReading);
}}else{logWidgetInfo(freshReading);
}result.old=freshReading;
result.fresh=UNDEFINED;
}}}}function logWidgetInfo(freshReading){freshReading.w=getIntegerValue(freshReading.w);
freshReading.h=getIntegerValue(freshReading.h);
freshReading.x=getIntegerValue(freshReading.x);
freshReading.y=getIntegerValue(freshReading.y);
logs.push(freshReading);
}function collectFeatureInfo(now,pageOffset,feature){if(!feature){return;
}var id=feature.id,result,offset,widthHeight,intersection,rectangle=getBoundingRectangle(pageOffset,feature);
if(!rectangle||!id){return;
}result={n:id,w:rectangle.w,h:rectangle.h,d:rectangle.d,x:rectangle.x,y:rectangle.y,z:0,t:now,k:"ewi"};
if(!result.d&&(CSM.useCelFF==DEFAULT_BEHAVIOR)){intersection=getIntersection(result,vpi);
}if(intersection){intersection.x-=vpi.x;
intersection.y-=vpi.y;
result.z=isInFront(feature,intersection)?1:0;
}results[id]=results[id]||{};
if(!results[id].old){addOneShotInfo(id,feature,result);
}if(!result.d){results[id].fresh=result;
}else{results[id].fresh=UNDEFINED;
}}function getBoundingRectangle(pageOffset,feature){if(!pageOffset||!feature||!feature.getBoundingClientRect){return;
}var boundlingClientRectangle=feature.getBoundingClientRect(),style=win.getComputedStyle?win.getComputedStyle(feature):feature.currentStyle,width=boundlingClientRectangle.width,height=boundlingClientRectangle.height;
return{x:boundlingClientRectangle.left+pageOffset.x||0,y:boundlingClientRectangle.top+pageOffset.y||0,w:width!==UNDEFINED?width:feature.offsetWidth||0,h:height!==UNDEFINED?height:feature.offsetHeight||0,d:(style!==UNDEFINED)&&(style.display==="none")?1:0};
}function getPageOffset(){var clientTop,clientLeft,xOffset=win.pageXOffset,yOffset=win.pageYOffset;
if(xOffset===UNDEFINED||yOffset===UNDEFINED){clientTop=(docElement?docElement.clientTop:0)||(body?body.clientTop:0);
clientLeft=(docElement?docElement.clientLeft:0)||(body?body.clientLeft:0);
xOffset=((docElement?docElement.scrollLeft:0)||(body?body.scrollLeft:0))-clientLeft;
yOffset=((docElement?docElement.scrollTop:0)||(body?body.scrollTop:0))-clientTop;
}return{x:xOffset,y:yOffset};
}function addOneShotInfo(id,feature,result){if(collectedOneShotInfo[id]){return;
}collectedOneShotInfo[id]=1;
result.cl=feature.className;
}function getIntegerValue(string){return win.parseInt?win.parseInt(string,10):-1;
}function intersect(a,b,c,d){if(a<d&&b>c){var overlap={p:a,q:b};
if(a<c){overlap.p=c;
}if(b>d){overlap.q=d;
}return overlap;
}}function getIntersection(rectangleA,rectangleB){if(rectangleA&&rectangleB){var xAxisIntersection,yAxisIntersection;
yAxisIntersection=intersect(rectangleA.y,rectangleA.y+rectangleA.h,rectangleB.y,rectangleB.y+rectangleB.h);
if(!yAxisIntersection){return;
}xAxisIntersection=intersect(rectangleA.x,rectangleA.x+rectangleA.w,rectangleB.x,rectangleB.x+rectangleB.w);
if(!xAxisIntersection){return;
}return{x:xAxisIntersection.p,y:yAxisIntersection.p,w:xAxisIntersection.q-xAxisIntersection.p,h:yAxisIntersection.q-yAxisIntersection.p};
}}function isInFront(widget,widgetInfo){if(CSM.useCelFF!=DEFAULT_BEHAVIOR){return 1;
}if(!doc.elementFromPoint){return;
}var centerOfWidget={x:widgetInfo.x+(widgetInfo.w/2),y:widgetInfo.y+(widgetInfo.h/2)},elementInFront;
elementInFront=doc.elementFromPoint(centerOfWidget.x,centerOfWidget.y);
if(elementInFront){return matchAncestor(elementInFront,widget);
}}function matchAncestor(element,ancestor){do{if(element===ancestor){return true;
}element=element.parentNode;
}while(element);
return false;
}function compareWithTollerance(a,b){return(a===b)||(Math.abs(a-b)<3);
}return{on:function(options){docElement=doc.documentElement;
body=doc.body;
sstimespan=options.timespan||100;
delta=options.ts;
namespace=options.ns;
MAX_RUNNING_TIME=options.mrt||10;
SNAPSHOT_DELAY=0,jQuery=win.jQuery;
MAX_RUNNING_TIME=(CSM.useCelFF==INCREASED_MAX_RUNNING_TIME?100:MAX_RUNNING_TIME);
MAX_RUNNING_TIME=(CSM.useCelFF==MAX_RUNNING_TIME_20?20:MAX_RUNNING_TIME);
MAX_RUNNING_TIME=(CSM.useCelFF==MAX_RUNNING_TIME_30?30:MAX_RUNNING_TIME);
MAX_RUNNING_TIME=(CSM.useCelFF==MAX_RUNNING_TIME_50?50:MAX_RUNNING_TIME);
MAX_RUNNING_TIME=(CSM.useCelFF==MAX_RUNNING_TIME_100?100:MAX_RUNNING_TIME);
SNAPSHOT_DELAY=(CSM.useCelFF==START_AFTER_ONLOAD_1?1000:SNAPSHOT_DELAY);
SNAPSHOT_DELAY=(CSM.useCelFF==START_AFTER_ONLOAD_2?2000:SNAPSHOT_DELAY);
SNAPSHOT_DELAY=(CSM.useCelFF==START_AFTER_ONLOAD_3?3000:SNAPSHOT_DELAY);
sstimespan=(CSM.useCelFF==SNAPSHOT_ONE_SECOND?1000:sstimespan);
function start(){setTimeout(snapshot,SNAPSHOT_DELAY);
}if((ue.deffered)||((CSM.useCelFF!=START_AFTER_ONLOAD)&&(CSM.useCelFF!=START_AFTER_ONLOAD_1)&&(CSM.useCelFF!=START_AFTER_ONLOAD_2)&&(CSM.useCelFF!=START_AFTER_ONLOAD_3))){start();
}else{if(ue.attach){ue.attach("load",start);
}}if(typeof uex=="function"){uex("ld",scopeName,{wb:1});
}},ready:function(){return win.jQuery&&win.ue_vpm?true:false;
},reset:function(){results={};
}};
})(window,document);
if(CSM.ue_cel){CSM.ue_cel.registerModule("features module",CSM.ue_fem);
}})(ue_csm);
