(function(a){var m=a.ue_err_chan||"jserr",i="FATAL",g="v5",e=20,l=256,j=/\(?([^\s]*):(\d+):\d+\)?/,b=/.*@(.*):(\d*)/;
function k(n){if(n){return n.replace(/^\s+|\s+$/g,"");
}}function d(n){if(!n||!n.s){return;
}var o,p=n.s.length>0?n.s[0]:"",q=n.s.length>1?n.s[1]:"";
if(p){o=p.match(b);
}if((!o||o.length!=3)&&q){o=q.match(j);
}if(o&&o.length==3){n.f=o[1];
n.l=o[2];
}}function c(p,v){if(!p){return{};
}var q={m:(v.m||v.message||"")+(p.m||p.message||"Unknown error"),f:(p.f||p.sourceURL||p.fileName),l:(p.l||p.line||p.lineNumber),c:p.c?""+p.c:p.c,s:[],name:p.name,type:p.type,csm:g+" "+(p.fromOnError?"onerror":"ueLogError")},u,t,o,x,r=0,s=0,n,w;
u=p.stack||(p.err?p.err.stack:"");
q.pageURL=v.pageURL||(""+(window.location?window.location.href:""))||"missing";
q.logLevel=v.logLevel||i;
w=v.attribution;
if(w){q.attribution=""+w;
}if(u&&u.split){q.csm+=" stack";
t=u.split("\n");
while(r<t.length&&q.s.length<e){o=t[r++];
if(o){q.s.push(k(o));
}}}else{q.csm+=" callee";
x=(p.args||arguments).callee;
r=0;
s=0;
while(x&&r<e){n=l;
if(!x.skipTrace){o=x.toString();
if(o&&o.substr){n=(s==0?4*l:n);
n=(s==1?2*l:n);
q.s.push(o.substr(0,n));
s++;
}}x=x.caller;
r++;
}}if(!q.f&&q.s.length>0){d(q);
}return q;
}function h(o,n){if(!o){return;
}a.ue.log(c(o,n),n.channel||m,{n:1});
}function f(p,o){if((!p)||(a.ue_err.ec>a.ue_err.mxe)){return;
}a.ue_err.ec++;
a.ue_err.ter.push(p);
o=o||{};
var n=p.logLevel||o.logLevel;
o.logLevel=n;
o.attribution=p.attribution||o.attribution;
if(!n||(n==i)){ue_err.ecf++;
}h(p,o);
}h.skipTrace=1;
c.skipTrace=1;
f.skipTrace=1;
(function(){if(!a.ue_err.erl){return;
}var n=a.ue_err.erl.length,o,p;
for(o=0;
o<n;
o++){p=a.ue_err.erl[o];
h(p.ex,p.info);
}ue_err.erl=[];
})();
a.ueLogError=f;
})(ue_csm);
